add batch processing for article history updates in the database

diff --git a/WP_article_collector/Dockerfile b/WP_article_collector/Dockerfile
--- a/WP_article_collector/Dockerfile
+++ b/WP_article_collector/Dockerfile
@@ -14,7 +14,7 @@ COPY wikipedia-histories /app/wikipedia-histories
 RUN pip install --no-cache-dir -e /app/wikipedia-histories
 
 # Create a wrapper script to run the application and then remove the container
-RUN echo '#!/bin/sh\npython run_based_summary.py "$@"\nexit_code=$?\n[ "$exit_code" -ne 0 ] && echo "Error: Application exited with code $exit_code"\nexit $exit_code' > /app/entrypoint.sh && \
+RUN echo '#!/bin/sh\npython run.py "$@"\nexit_code=$?\n[ "$exit_code" -ne 0 ] && echo "Error: Application exited with code $exit_code"\nexit $exit_code' > /app/entrypoint.sh && \
     chmod +x /app/entrypoint.sh
 
 ENTRYPOINT ["/app/entrypoint.sh"]
